---
title: "EDO Estimation of parameters : the logistic growth"
format: html
editor: visual
---

# Introduction

This document aims to be a presentation of a logistic growth simulation: from the data simulation to the estimation of the parameters. The following document will thus be organized in two parts : the data simulation and the estimation of the parameters.

# Data Simulation

We first simulate the data on which we will illustrate two estimation methods. The simulation is based on the logistic growth (Verhulst model). The ordinary differential equation describing the logistic growth is defined as 
$$
\frac{dN}{dt} = rN(1-\frac{N}{K})
$$

where N is the size of a population, r is the growth rate and K is the carrying capacity. Thankfully, there is an explicit solution of the Verhulst model that allows us to simulate the data. For each x (the time), we calculate the deterministic solution and add a noise, a centered, normally distributed deviation from the deterministic model.

```{r}
# Parameters
time <- seq(0, 25, 0.25)
r <- 0.5
K <- 100
error <- 5
y0 <- 1

# Logistic growth function with error
logistic <- function(t, r, K, y0, error) {
  growth <- K / (1 + ((K - y0) / y0) * exp(-r * t))
  return(growth + rnorm(1, mean = 0, sd = error))  # Add random error
}

# Apply the logistic function over the time vector
y <- sapply(time, logistic, r = r, K = K, y0 = y0, error = error)

# Plot the result
plot(time, y, col = "blue", xlab = "Time", ylab = "Population", main = "Logistic Growth with Error")
```

# Estimation of the parameters

We have p parameters $\theta = (\theta_1,\theta_2,...,\theta_p)$.

## General theory

### Maximum likelihood

Likelihood corresponds to the probability of observing the data, knowing the parameters $\theta$. The likelihood function is as follows : $$
L(\theta) = \prod_{i=1}^n f(x_i , \theta)
$$ In this function, $x_i$ corresponds to the observations and $f(x_i,\theta)$ corresponds to the probability density function of the random variable X.

The maximum likelihood method consists of determining the $\hat\theta$ which allows obtaining the highest possible likelihood value : $$
\hat\theta = \arg\max_\theta L(\theta)
$$ If the errors of the data are independent and identically distributed, this method is equivalent to the least squares method : $$
\hat{\theta} = \arg\max_{\theta} L(\theta) = \arg\min_{\theta} SCE(\theta)
$$ We prefer to work on the logarithm of the product $L(\theta)$ as it converts products into sums : $$
LL(\theta) = ln(L(\theta)) = \sum_{i=1}^n lnf(x_i,\theta)
$$
