<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Principal Component Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-169b6d0432b1a799c6e7691d07d1a7fb.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="theme.scss">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/MarieEtienne/stats-reminders"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./instructions.html"> 
<span class="menu-text">Instructions</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-two-examples" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Two examples</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-two-examples">    
        <li>
    <a class="dropdown-item" href="./r_chapter.html">
 <span class="dropdown-text">Basic quarto cross ref example</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Penguins_chapter.html">
 <span class="dropdown-text">Penguins example</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-linear-model" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Linear Model</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-linear-model">    
        <li>
    <a class="dropdown-item" href="./Linear_Model_1.html">
 <span class="dropdown-text">Penguins</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Linear_Model_2.html">
 <span class="dropdown-text">Badgers</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-factorial-analysis" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Factorial Analysis</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-factorial-analysis">    
        <li class="dropdown-header">pca.qmd</li>
        <li class="dropdown-header">cca.qmd</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-differential-equation" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Differential Equation</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-differential-equation">    
        <li class="dropdown-header">EDO_ESTIMATION.qmd</li>
        <li class="dropdown-header">EDO_LOTKA_VOLTERRA.qmd</li>
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction-to-the-principal-component-analysis" id="toc-introduction-to-the-principal-component-analysis" class="nav-link active" data-scroll-target="#introduction-to-the-principal-component-analysis"><strong>Introduction to the Principal Component Analysis</strong></a></li>
  <li><a href="#ecological-exemple" id="toc-ecological-exemple" class="nav-link" data-scroll-target="#ecological-exemple">Ecological Exemple</a>
  <ul class="collapse">
  <li><a href="#eye-size-evolution-in-spider" id="toc-eye-size-evolution-in-spider" class="nav-link" data-scroll-target="#eye-size-evolution-in-spider">Eye size evolution in spider</a></li>
  <li><a href="#data-preprocessing" id="toc-data-preprocessing" class="nav-link" data-scroll-target="#data-preprocessing">Data preprocessing</a></li>
  <li><a href="#packages" id="toc-packages" class="nav-link" data-scroll-target="#packages">Packages</a></li>
  <li><a href="#pca-analysis" id="toc-pca-analysis" class="nav-link" data-scroll-target="#pca-analysis">PCA Analysis</a>
  <ul class="collapse">
  <li><a href="#interpretation-tips" id="toc-interpretation-tips" class="nav-link" data-scroll-target="#interpretation-tips">Interpretation tips :</a></li>
  </ul></li>
  <li><a href="#data-visualisation-and-interpretation" id="toc-data-visualisation-and-interpretation" class="nav-link" data-scroll-target="#data-visualisation-and-interpretation">Data visualisation and interpretation</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Principal Component Analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Kilian Rocher, Océane Picot, Alexia Orhan </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction-to-the-principal-component-analysis" class="level1">
<h1><strong>Introduction to the Principal Component Analysis</strong></h1>
<p><strong>Principal Component Analysis</strong> (PCA) is a dimension reduction technique widely used in data analysis and machine learning for simplifying complex datasets. It helps us understand high-dimensional data by reducing the number of variables we need to consider while keeping as much of the original information as possible.</p>
<p>The main goals are to <strong>reduce the number of variables</strong> into a new set of uncorrelated variables called <strong>principal components</strong>, to <strong>visualize high-dimensional data</strong> in 2D or 3D, to <strong>detect patterns</strong>, clusters and outliers, and to <strong>remove noise and redundant information</strong>. For example, if you get a data set with 10 correlated variables, PCA can reduce it to 2 or 3 principal components that explains 90% of the variance and makes it easier to visualize.</p>
<p>The PCA, values have to be <strong>quantitative</strong>, and organized in a <em>n x p</em> matrix with <em>p</em> observations and <em>n</em> variables</p>
<p>We will be using the R package <em>FactoMineR</em> (<span class="citation" data-cites="factominer_le2008">Lê, Josse, and Husson (<a href="#ref-factominer_le2008" role="doc-biblioref">2008</a>)</span>).</p>
</section>
<section id="ecological-exemple" class="level1">
<h1>Ecological Exemple</h1>
<section id="eye-size-evolution-in-spider" class="level2">
<h2 class="anchored" data-anchor-id="eye-size-evolution-in-spider">Eye size evolution in spider</h2>
<p>Our example is based on the article <span class="citation" data-cites="Chong2024">Chong (<a href="#ref-Chong2024" role="doc-biblioref">2024</a>)</span>. This study examines how eye size evolves in spiders, which possess up to four pairs of eyes of variable sizes. Researchers analyzed 1,098 individuals from 39 species and supplemented their data with approximately 474 additional species.</p>
<p>The researchers measured four different eye pairs simultaneously. PCA reduces this 4-dimensional dataset into <strong>interpretable components</strong>, making it easier to visualize and understand patterns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>spiders <span class="ot">&lt;-</span><span class="fu">read.delim</span>(<span class="st">"S2_WolffData-Curated.txt"</span>,<span class="at">header =</span> <span class="cn">TRUE</span>, <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span>) <span class="co">#data importation</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(spiders)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                 terminal              Family   
 Actinopodidae_Actinopus_insignis    :  1   Araneidae     : 24  
 Actinopodidae_Missulena_granulosa   :  1   Linyphiidae   : 21  
 Agelenidae_Agelena_labyrinthica     :  1   Theridiidae   : 20  
 Agelenidae_Barronopsis_barrowsi     :  1   Salticidae    : 17  
 Agelenidae_Draconarius_cangshanensis:  1   Tetragnathidae: 17  
 Agelenidae_Eratigena_atrica         :  1   Thomisidae    : 16  
 (Other)                             :467   (Other)       :358  
       CW              AME              ALE              PME        
 Min.   : 0.240   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000  
 1st Qu.: 1.090   1st Qu.:0.0600   1st Qu.:0.0800   1st Qu.:0.0800  
 Median : 2.000   Median :0.1100   Median :0.1200   Median :0.1200  
 Mean   : 2.453   Mean   :0.1434   Mean   :0.1535   Mean   :0.1471  
 3rd Qu.: 3.000   3rd Qu.:0.1700   3rd Qu.:0.1900   3rd Qu.:0.1800  
 Max.   :16.000   Max.   :0.9900   Max.   :0.8000   Max.   :0.7400  
                                                                    
      PLE            builder           orbweb          hanging      
 Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000  
 1st Qu.:0.0856   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000  
 Median :0.1300   Median :1.0000   Median :0.0000   Median :0.0000  
 Mean   :0.1556   Mean   :0.5074   Mean   :0.1163   Mean   :0.3784  
 3rd Qu.:0.1900   3rd Qu.:1.0000   3rd Qu.:0.0000   3rd Qu.:1.0000  
 Max.   :0.7000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000  
                                                                    
     guild     visual.incl.static visual.pursuit       active      
 Min.   :1.0   Min.   :0.0000     Min.   :0.0000   Min.   :0.0000  
 1st Qu.:3.0   1st Qu.:0.0000     1st Qu.:0.0000   1st Qu.:0.0000  
 Median :3.0   Median :0.0000     Median :0.0000   Median :0.0000  
 Mean   :3.6   Mean   :0.1332     Mean   :0.1015   Mean   :0.1831  
 3rd Qu.:4.0   3rd Qu.:0.0000     3rd Qu.:0.0000   3rd Qu.:0.0000  
 Max.   :6.0   Max.   :1.0000     Max.   :1.0000   Max.   :1.0000  
                                                   NA's   :107     
    Largest          Smallest           rAME              rALE        
 Min.   :0.0200   Min.   :0.0000   Min.   :0.00000   Min.   :0.00000  
 1st Qu.:0.1000   1st Qu.:0.0500   1st Qu.:0.04255   1st Qu.:0.05333  
 Median :0.1500   Median :0.0900   Median :0.05882   Median :0.06875  
 Mean   :0.1935   Mean   :0.1046   Mean   :0.06448   Mean   :0.07310  
 3rd Qu.:0.2200   3rd Qu.:0.1300   3rd Qu.:0.07692   3rd Qu.:0.08602  
 Max.   :0.9900   Max.   :0.5000   Max.   :0.38462   Max.   :0.23077  
                                                                      
      rPME              rPLE            rLargest         rSmallest      
 Min.   :0.00000   Min.   :0.00000   Min.   :0.02273   Min.   :0.00000  
 1st Qu.:0.05128   1st Qu.:0.05446   1st Qu.:0.06587   1st Qu.:0.03550  
 Median :0.06548   Median :0.06859   Median :0.08036   Median :0.04808  
 Mean   :0.06981   Mean   :0.07316   Mean   :0.09051   Mean   :0.04734  
 3rd Qu.:0.08520   3rd Qu.:0.08696   3rd Qu.:0.10000   3rd Qu.:0.06015  
 Max.   :0.28794   Max.   :0.18750   Max.   :0.38462   Max.   :0.18235  
                                                                        
      rvar                var           
 Min.   :0.000e+00   Min.   :0.0000000  
 1st Qu.:7.308e-05   1st Qu.:0.0001667  
 Median :1.587e-04   Median :0.0005667  
 Mean   :7.930e-04   Mean   :0.0036358  
 3rd Qu.:4.614e-04   3rd Qu.:0.0020667  
 Max.   :2.152e-02   Max.   :0.0927333  
                                        </code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(spiders)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                              terminal        Family    CW  AME  ALE  PME  PLE
1     Actinopodidae_Actinopus_insignis Actinopodidae  5.40 0.16 0.40 0.24 0.32
2    Actinopodidae_Missulena_granulosa Actinopodidae 11.00 0.25 0.25 0.20 0.25
3      Agelenidae_Agelena_labyrinthica    Agelenidae  3.60 0.28 0.26 0.22 0.24
4      Agelenidae_Barronopsis_barrowsi    Agelenidae  1.90 0.15 0.15 0.15 0.15
5 Agelenidae_Draconarius_cangshanensis    Agelenidae  3.06 0.15 0.20 0.18 0.20
6          Agelenidae_Eratigena_atrica    Agelenidae  4.10 0.26 0.27 0.23 0.24
  builder orbweb hanging guild visual.incl.static visual.pursuit active Largest
1       1      0       0     1                  0              0      0    0.40
2       1      0       0     1                  0              0      0    0.25
3       1      0       0     2                  0              0      0    0.28
4       1      0       0     2                  0              0      0    0.15
5       1      0       0     2                  0              0      0    0.20
6       1      0       0     2                  0              0      0    0.27
  Smallest       rAME       rALE       rPME       rPLE   rLargest  rSmallest
1     0.16 0.02962963 0.07407407 0.04444444 0.05925926 0.07407407 0.02962963
2     0.20 0.02272727 0.02272727 0.01818182 0.02272727 0.02272727 0.01818182
3     0.22 0.07777778 0.07222222 0.06111111 0.06666667 0.07777778 0.06111111
4     0.15 0.07894737 0.07894737 0.07894737 0.07894737 0.07894737 0.07894737
5     0.15 0.04901961 0.06535948 0.05882353 0.06535948 0.06535948 0.04901961
6     0.23 0.06341463 0.06585366 0.05609756 0.05853659 0.06585366 0.05609756
         rvar         var
1 3.65798e-04 0.010666667
2 5.16529e-06 0.000625000
3 5.14403e-05 0.000666667
4 0.00000e+00 0.000000000
5 5.96281e-05 0.000558333
6 1.98295e-05 0.000333333</code></pre>
</div>
</div>
<p>The raw data set is composed of 473 observations of 24 variables .</p>
</section>
<section id="data-preprocessing" class="level2">
<h2 class="anchored" data-anchor-id="data-preprocessing">Data preprocessing</h2>
<p>We don’t want to analyze all species so we just keep the families. Also we keep relative variables instead of absolute ones in order to be able to compare spider families with different sizes.</p>
<p>Description of the quantitative variables :</p>
<ul>
<li><p>rAME : relative Anterior Median Eyes (colored in yellow in <span class="citation" data-cites="fig1">(<a href="#ref-fig1" role="doc-biblioref"><strong>fig1?</strong></a>)</span>)</p></li>
<li><p>rALE : relative Anterior Lateral Eyes (colored in red in <span class="citation" data-cites="fig1">(<a href="#ref-fig1" role="doc-biblioref"><strong>fig1?</strong></a>)</span>)</p></li>
<li><p>rPME : relative Posterior Median Eyes (colored in blue in <span class="citation" data-cites="fig1">(<a href="#ref-fig1" role="doc-biblioref"><strong>fig1?</strong></a>)</span>)</p></li>
<li><p>rPLE : relative Posterior Lateral Eyes (colored in green in <span class="citation" data-cites="fig1">(<a href="#ref-fig1" role="doc-biblioref"><strong>fig1?</strong></a>)</span>)</p></li>
</ul>
<div id="fig1" style="text-align:center">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="arrangements_of_spider_eyes.jpg" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption>Figure 1 — Typical arrangements of spider eyes and their modification across spider families</figcaption>
</figure>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>spiders <span class="ot">&lt;-</span> <span class="fu">read.delim</span>(<span class="st">"S2_WolffData-Curated.txt"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>, <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>spiders <span class="ot">&lt;-</span> spiders[<span class="fu">c</span>(<span class="st">"Family"</span>,<span class="st">"rAME"</span>,<span class="st">"rALE"</span>,<span class="st">"rPME"</span>,<span class="st">"rPLE"</span>)] <span class="co">#selection of variables</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>spiders <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(spiders)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The PCA methodology begins by <strong>standardizing the data</strong> (center and scale variables)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>spiders<span class="sc">$</span>rALE <span class="ot">&lt;-</span> (spiders<span class="sc">$</span>rALE<span class="sc">-</span><span class="fu">mean</span>(spiders<span class="sc">$</span>rALE))<span class="sc">/</span><span class="fu">sd</span>(spiders<span class="sc">$</span>rALE)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>spiders<span class="sc">$</span>rAME <span class="ot">&lt;-</span> (spiders<span class="sc">$</span>rAME<span class="sc">-</span><span class="fu">mean</span>(spiders<span class="sc">$</span>rAME))<span class="sc">/</span><span class="fu">sd</span>(spiders<span class="sc">$</span>rAME)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>spiders<span class="sc">$</span>rPLE <span class="ot">&lt;-</span> (spiders<span class="sc">$</span>rPLE<span class="sc">-</span><span class="fu">mean</span>(spiders<span class="sc">$</span>rPLE))<span class="sc">/</span><span class="fu">sd</span>(spiders<span class="sc">$</span>rPLE)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>spiders<span class="sc">$</span>rPME <span class="ot">&lt;-</span> (spiders<span class="sc">$</span>rPME<span class="sc">-</span><span class="fu">mean</span>(spiders<span class="sc">$</span>rPME))<span class="sc">/</span><span class="fu">sd</span>(spiders<span class="sc">$</span>rPME)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(spiders) <span class="co">#all means are equal to 0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Family         rAME              rALE              rPME        
 Araneidae     : 24   Min.   :-1.2774   Min.   :-2.4207   Min.   :-2.3562  
 Linyphiidae   : 21   1st Qu.:-0.4344   1st Qu.:-0.6547   1st Qu.:-0.6253  
 Theridiidae   : 20   Median :-0.1120   Median :-0.1442   Median :-0.1462  
 Salticidae    : 17   Mean   : 0.0000   Mean   : 0.0000   Mean   : 0.0000  
 Tetragnathidae: 17   3rd Qu.: 0.2465   3rd Qu.: 0.4277   3rd Qu.: 0.5196  
 Thomisidae    : 16   Max.   : 6.3423   Max.   : 5.2207   Max.   : 7.3626  
 (Other)       :358                                                        
      rPLE        
 Min.   :-2.5659  
 1st Qu.:-0.6560  
 Median :-0.1602  
 Mean   : 0.0000  
 3rd Qu.: 0.4839  
 Max.   : 4.0103  
                  </code></pre>
</div>
</div>
</section>
<section id="packages" class="level2">
<h2 class="anchored" data-anchor-id="packages">Packages</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(FactoMineR) <span class="co">#to realize the PCA</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(factoextra) <span class="co">#to visualize data</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: ggplot2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Welcome! Want to learn more? See two factoextra-related books at https://goo.gl/ve3WBa</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2) <span class="co">#to plot the results</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="pca-analysis" class="level2">
<h2 class="anchored" data-anchor-id="pca-analysis">PCA Analysis</h2>
<p>We use the <strong>PCA</strong> function from <em>FactoMineR</em> (<span class="citation" data-cites="factominer_le2008">Lê, Josse, and Husson (<a href="#ref-factominer_le2008" role="doc-biblioref">2008</a>)</span>). Through a linear algebra decomposition called the <strong>singular value decomposition</strong> (SVD), PCA identifies orthogonal directions in the data space—<strong>the principal components</strong>—ordered by the amount of variance they explain, with the first component capturing the maximum variance, the second capturing the next highest variance while being uncorrelated with the first, and so on.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>res.pca <span class="ot">&lt;-</span> <span class="fu">PCA</span>(spiders,</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">scale.unit =</span> <span class="cn">FALSE</span>,    <span class="co"># already centered-reduced</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">quali.sup =</span> <span class="dv">1</span>, <span class="co"># "Family" is qualitative and illustrative</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">graph =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The output of the <code>PCA()</code> is a list of several components :</p>
<ul>
<li><p><code>$eig</code> (<strong>Eigenvalues)</strong></p>
<ul>
<li>A matrix containing eigenvalues, percentage of variance, and cumulative percentage of variance for each principal component</li>
</ul></li>
<li><p><code>$var</code> <strong>(Results for Variables)</strong></p>
<ul>
<li><p><code>$var$coord</code>: Coordinates (correlations) of variables with principal components</p></li>
<li><p><code>$var$cor</code>: Correlations between variables and dimensions (same as coord for standardized PCA)</p></li>
<li><p><code>$var$cos2</code>: Quality of representation - squared cosine values showing how well variables are represented on each dimension</p></li>
<li><p><code>$var$contrib</code>: Contributions of variables to each dimension (in percentage)</p></li>
</ul></li>
<li><p><code>$ind</code>&nbsp;(Results for Individuals/Observations)</p>
<ul>
<li><p><code>$ind$coord</code>: Coordinates of individuals on the principal components</p></li>
<li><p><code>$ind$cos2</code>: Quality of representation of individuals on each dimension</p></li>
<li><p><code>$ind$contrib</code>: Contributions of individuals to each dimension</p></li>
<li><p><code>$ind$dist</code>: Squared distance of individuals to the origin</p></li>
</ul></li>
<li><p><code>$call</code>&nbsp;(Call Information)</p>
<ul>
<li>Contains information about the function call</li>
</ul></li>
<li><p><code>$svd</code>&nbsp;(Singular Value Decomposition)</p>
<ul>
<li>Contains the raw SVD components (if you want to have a deeper mathematical understanding of PCA)</li>
</ul></li>
</ul>
<section id="interpretation-tips" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-tips">Interpretation tips :</h3>
<ul>
<li><p><strong>Coordinates</strong> indicate <strong>the position</strong> of a variable or individual on a dimension.</p>
<ul>
<li><p>For Variables :</p>
<ul>
<li>Coordinates = <strong>correlation</strong> between the variable and the principal component, it measures the strength and direction of the relationship</li>
</ul></li>
<li><p>For Individuals :</p>
<ul>
<li>Coordinates = position of the individual on the axis (score), it measures the relative position of the individual</li>
</ul></li>
</ul></li>
<li><p><strong>Contributions</strong> indicate <strong>the weight</strong> of a variable or individual in the construction of the dimension.</p>
<ul>
<li><p>For variables it measures the relative importance in constructing the axes</p></li>
<li><p>For individuals it measures the individual’s influence</p></li>
</ul></li>
<li><p><strong>Cos²</strong> values range from 0 to 1 and measures <strong>how much information about an element is preserved</strong> when we project it onto the principal components. When close to 1, it’s a good representation. <strong>Only well projected variables can be interpreted !</strong></p></li>
</ul>
</section>
</section>
<section id="data-visualisation-and-interpretation" class="level2">
<h2 class="anchored" data-anchor-id="data-visualisation-and-interpretation">Data visualisation and interpretation</h2>
<p>To visualize the results from the PCA, we can analyse the percentage of inertia explained by the principal components through the <strong>graph of inertia.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>res.pca<span class="sc">$</span>eig</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       eigenvalue percentage of variance cumulative percentage of variance
comp 1  2.4713096              61.913635                          61.91364
comp 2  0.9667296              24.219444                          86.13308
comp 3  0.3841774               9.624784                          95.75786
comp 4  0.1693267               4.242137                         100.00000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_eig</span>(res.pca, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">100</span>), <span class="at">geom=</span><span class="st">'bar'</span>, <span class="at">main=</span><span class="st">'Percentage of inertia explained by axes'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in geom_bar(stat = "identity", fill = barfill, color = barcolor, :
Ignoring empty aesthetic: `width`.</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="PCA_files/figure-html/PCA_inertia-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Table of eigenvalue and percentage of variance</figcaption>
</figure>
</div>
</div>
<p>Percentage of inertia explained by axes</p>
</div>
<p>The two first axis explain more than 86% of the total variance so only two main components are selected for the analysis. The first dimension explains 61.9% of the variance while the second dimension explains 24.2% of the variance.</p>
<p>Only well projected variables and individuals can be interpreted. The sum of cos2 on Dim.1 and Dim.2 should be around 1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>res.pca<span class="sc">$</span>var<span class="sc">$</span>cos2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Dim.1      Dim.2        Dim.3       Dim.4
rAME 0.3649931 0.51987186 0.1099967401 0.005138294
rALE 0.7625624 0.01511613 0.1922797407 0.030041770
rPME 0.4674557 0.42280707 0.0824978808 0.027239329
rPLE 0.8815342 0.01098269 0.0002169861 0.107266100</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(res.pca<span class="sc">$</span>ind<span class="sc">$</span>cos2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Dim.1        Dim.2        Dim.3       Dim.4
1 0.5718158 0.0092466126 4.162814e-01 0.002656177
2 0.9693135 0.0286383335 8.082148e-05 0.001967393
3 0.1528857 0.7973347485 4.610207e-03 0.045169352
4 0.8723660 0.0002976105 9.319961e-02 0.034136780
5 0.9176860 0.0008392141 5.859037e-02 0.022884419
6 0.7853358 0.1852413189 3.558803e-03 0.025864108</code></pre>
</div>
<p>Projection quality of variables and individuals</p>
</div>
<p>The variables and individuals are well projected and can be interpreted.</p>
<p>We can also see how the variables contribute to the the two principal components.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>res.pca<span class="sc">$</span>var<span class="sc">$</span>contrib</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Dim.1     Dim.2       Dim.3     Dim.4
rAME 14.73799 53.662655 28.57122394  3.028128
rALE 30.79137  1.560330 49.94391220 17.704384
rPME 18.87531 43.643350 21.42850257 16.052833
rPLE 35.59532  1.133665  0.05636129 63.214655</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_pca_var</span>(res.pca,</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">col.var =</span> <span class="st">"contrib"</span>,</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">gradient.cols =</span> <span class="fu">c</span>(<span class="st">"blue"</span>, <span class="st">"yellow"</span>, <span class="st">"red"</span>),</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">repel =</span> <span class="cn">TRUE</span>,</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">title =</span> <span class="st">"PCA variable correlation plot"</span>) <span class="co">#show how relative eyed sizes are correlated</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.
ℹ The deprecated feature was likely used in the ggpubr package.
  Please report the issue at &lt;https://github.com/kassambara/ggpubr/issues&gt;.</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="PCA_files/figure-html/var_contrib-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Table of contribution of variables to the axes</figcaption>
</figure>
</div>
</div>
<p>Contribution of variables to the axes</p>
</div>
<p>All variables are contributing a lot to the first axis. However, lateral eyes (rALE and rPLE) explain the best the axis with contributions higher than 30%. On the other hand, medium eyes (rAME and rPME) explain the second axis with contributions respectively equal to 54% and 44%.</p>
<p>We can also plot the individuals into principal component space.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_pca_ind</span>(res.pca,</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">geom.ind =</span> <span class="st">"point"</span>,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">label =</span> <span class="st">"none"</span>,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">habillage =</span> spiders<span class="sc">$</span>Family, <span class="co">#to see if a family looks to contribute more to the axis</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">legend =</span> <span class="st">"none"</span>,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">repel =</span> <span class="cn">TRUE</span>,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">pointshape =</span> <span class="dv">19</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="PCA_files/figure-html/indiviual_graph-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Scatterplot of individuals on the two main axes</figcaption>
</figure>
</div>
</div>
</div>
<p>The individuals are mainly distributed along the first axis which can be interpreted as a gradient of variation in lateral eye size. Individuals are also concentrated around zero which means that a majority of spiders has similar eye proportions.</p>
<p>Because there are 106 families of species, we will concentrate only on the first height most frequent family in order to have a clearer vision.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>top_families <span class="ot">&lt;-</span> <span class="fu">names</span>(<span class="fu">sort</span>(<span class="fu">table</span>(spiders<span class="sc">$</span>Family), <span class="at">decreasing =</span> <span class="cn">TRUE</span>))[<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>] <span class="co">#only frequent families to have a clearer graph</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>spiders_sub <span class="ot">&lt;-</span> <span class="fu">subset</span>(spiders, Family <span class="sc">%in%</span> top_families)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>res.pca2 <span class="ot">&lt;-</span> <span class="fu">PCA</span>(spiders_sub, <span class="at">scale.unit =</span> <span class="cn">FALSE</span>, <span class="at">quali.sup =</span> <span class="dv">1</span>, <span class="at">graph =</span> <span class="cn">FALSE</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_pca_ind</span>(res.pca2, <span class="at">habillage =</span> spiders_sub<span class="sc">$</span>Family, </span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>             <span class="co">#palette = "Dark2", </span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>             <span class="co">#repel = TRUE,</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">select.ind =</span> <span class="fu">list</span>(<span class="at">name =</span> <span class="cn">NULL</span>, <span class="at">cos2 =</span> <span class="cn">NULL</span>, <span class="at">contrib =</span> <span class="cn">NULL</span>),</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">label=</span><span class="st">"none"</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>             )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="PCA_files/figure-html/indiviual_graph_selectind-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Scatterplot of individuals of the first height most frequent family on the two main axes</figcaption>
</figure>
</div>
</div>
</div>
<p>Graph of contributions by individuals :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#res.pca$ind$contrib</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Axis 1</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>top10_ind <span class="ot">&lt;-</span> <span class="fu">order</span>(res.pca<span class="sc">$</span>ind<span class="sc">$</span>contrib[,<span class="dv">1</span>], <span class="at">decreasing =</span> <span class="cn">TRUE</span>)[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>] <span class="co">#the 10 individuals contributing the most to the first axis</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>top10_ind_fam <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">Individual =</span> <span class="fu">rownames</span>(spiders)[top10_ind],</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Family =</span> spiders<span class="sc">$</span>Family[top10_ind],</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">Contribution =</span> res.pca<span class="sc">$</span>ind<span class="sc">$</span>contrib[top10_ind, <span class="dv">1</span>]</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>) <span class="co">#families associated to the individuals contributing the most</span></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>top10_ind_fam</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Individual        Family Contribution
394        394   Theridiidae     4.001470
321        321    Salticidae     3.920528
317        317    Salticidae     2.994396
324        324    Salticidae     2.670138
313        313    Salticidae     2.336463
314        314    Salticidae     2.251339
20          20      Anapidae     2.048994
316        316    Salticidae     2.026889
280        280 Physoglenidae     1.891939
315        315    Salticidae     1.884911</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Axis 2</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>top10_ind_2 <span class="ot">&lt;-</span> <span class="fu">order</span>(res.pca<span class="sc">$</span>ind<span class="sc">$</span>contrib[,<span class="dv">2</span>], <span class="at">decreasing =</span> <span class="cn">TRUE</span>)[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>] <span class="co">#the 10 individuals contributing the most to the first axis</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>top10_ind_fam_2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Individual =</span> <span class="fu">rownames</span>(spiders)[top10_ind_2],</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">Family =</span> spiders<span class="sc">$</span>Family[top10_ind_2],</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">Contribution =</span> res.pca<span class="sc">$</span>ind<span class="sc">$</span>contrib[top10_ind_2, <span class="dv">2</span>]</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>) <span class="co">#families associated to the individuals contributing the most</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>top10_ind_fam_2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Individual            Family Contribution
321        321        Salticidae     7.381965
105        105        Deinopidae     6.570819
315        315        Salticidae     5.036677
316        316        Salticidae     4.664661
317        317        Salticidae     4.484055
314        314        Salticidae     4.393568
326        326        Salticidae     3.579762
313        313        Salticidae     2.859800
104        104     Cycloctenidae     2.774391
359        359 Symphytognathidae     2.429119</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Axis 1</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">sort</span>(res.pca<span class="sc">$</span>ind<span class="sc">$</span>contrib[,<span class="dv">1</span>], <span class="at">decreasing =</span> <span class="cn">TRUE</span>), <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     394      321      317      324      313      314       20      316 
4.001470 3.920528 2.994396 2.670138 2.336463 2.251339 2.048994 2.026889 
     280      315 
1.891939 1.884911 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Axis 2</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">sort</span>(res.pca<span class="sc">$</span>ind<span class="sc">$</span>contrib[,<span class="dv">2</span>], <span class="at">decreasing =</span> <span class="cn">TRUE</span>), <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     321      105      315      316      317      314      326      313 
7.381965 6.570819 5.036677 4.664661 4.484055 4.393568 3.579762 2.859800 
     104      359 
2.774391 2.429119 </code></pre>
</div>
</div>
<p>When we visualise families, it looks like individuals from the <em>Salticidae</em> are atypical individuals because they are far on the first axis. In fact, looking at the contributions just above, those individuals have the highest contributions. For the first and the second axis, 7 out of 10 individuals are in the family <em>Salticidae</em>.</p>
<div style="text-align:center">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Salticidae.jpg" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption>Figure 2 — Family <em>Salticidae</em> contributing the most to explained variance.</figcaption>
</figure>
</div>
</div>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>According to <span class="citation" data-cites="var_contrib">(<a href="#ref-var_contrib" role="doc-biblioref"><strong>var_contrib?</strong></a>)</span>, the first axis is positively correlated with the relative size of both the anterior and posterior lateral eyes (the red and green ones in <span class="citation" data-cites="fig1">(<a href="#ref-fig1" role="doc-biblioref"><strong>fig1?</strong></a>)</span>). For the second axis, there seems to be an antagonistic relationship between the anterior and posterior eyes.</p>
<p>This provides information about how eye sizes evolve together. However, from an ecological perspective, it would be interesting to study whether body size or spider activity is linked to eye size, as done in the original article <span class="citation" data-cites="Chong2024">Chong (<a href="#ref-Chong2024" role="doc-biblioref">2024</a>)</span>. For example, we could test whether nocturnal spider species have larger eyes than diurnal ones.</p>
<p>We performed a PCA to visualize the relationships between variables. The goal was also to reduce the dimensionality of the dataset. However, since our dataset includes only four variables, it is not the most suitable example to demonstrate the advantages of factorial analysis.</p>



</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Chong2024" class="csl-entry" role="listitem">
Chong, Kaylin L. 2024. <span>“Allometry and Ecology Shape Eye Size Evolution in Spiders.”</span> <em>Current Biology</em>. <a href="https://doi.org/10.1016/j.cub.2024.06.020">https://doi.org/10.1016/j.cub.2024.06.020</a>.
</div>
<div id="ref-factominer_le2008" class="csl-entry" role="listitem">
Lê, Sébastien, Julie Josse, and François Husson. 2008. <span>“<span>FactoMineR</span>: A Package for Multivariate Analysis.”</span> <em>Journal of Statistical Software</em> 25 (1): 1–18. <a href="https://doi.org/10.18637/jss.v025.i01">https://doi.org/10.18637/jss.v025.i01</a>.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>